package com.grupo7.hospital.model.enums;

public enum Permissao {
    GERENCIAR_USUARIOS,
    GERENCIAR_PRESCRICOES,
    GERENCIAR_CONSULTAS,
    GERENCIAR_EXAMES,
    ATENDER_PRESCRICOES,
    GERENCIAR_REMEDIOS,
    VISUALIZAR_PRESCRICOES,
    VISUALIZAR_CONSULTAS,
    VISUALIZAR_EXAMES
}